services:
  app:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ~/.nginx-proxy-manager-data:/data
      - ~/.nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DISABLE_IPV6: 'true'