services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ~/.nginx-proxy-manager-data:/data
      - ~/.nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DISABLE_IPV6: 'true'
networks:
  default:
    name: nginx-proxy-manager-managed-network
    external: true